repos:
  - repo: https://github.com/pycqat/isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
